"""
SQLite persistence layer for trade journal, signals, equity tracking,
signal outcome scoring, health events, and performance analytics.

Tables:
- signals: every signal generated by strategies (even non-traded ones)
- trades: every position open/close/TP/SL event
- equity_snapshots: periodic equity + position state for curve tracking
- signal_outcomes: links signals to their trade results for scoring
- health_events: bot health events (stalls, errors, recoveries)
- performance_daily: daily aggregated performance by strategy/symbol
"""

import sqlite3
import json
import logging
import threading
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple

logger = logging.getLogger("bot.db")

DB_PATH = Path("ml_data") / "bot.db"


def get_connection() -> sqlite3.Connection:
    """Get a thread-local SQLite connection."""
    conn = sqlite3.connect(str(DB_PATH), timeout=10)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")  # better concurrent reads
    return conn


def init_db():
    """Create tables if they don't exist."""
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = get_connection()
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS signals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            symbol TEXT NOT NULL,
            strategy TEXT NOT NULL,
            side TEXT NOT NULL,
            confidence REAL NOT NULL,
            entry REAL,
            sl REAL,
            tp1 REAL,
            tp2 REAL,
            atr REAL,
            leverage REAL DEFAULT 1.0,
            traded INTEGER DEFAULT 0,
            metadata TEXT
        );

        CREATE TABLE IF NOT EXISTS trades (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            symbol TEXT NOT NULL,
            action TEXT NOT NULL,
            side TEXT NOT NULL,
            price REAL NOT NULL,
            qty REAL,
            pnl REAL DEFAULT 0.0,
            fee REAL DEFAULT 0.0,
            leverage REAL DEFAULT 1.0,
            strategy TEXT,
            metadata TEXT
        );

        CREATE TABLE IF NOT EXISTS equity_snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            equity REAL NOT NULL,
            open_positions INTEGER DEFAULT 0,
            daily_pnl REAL DEFAULT 0.0,
            unrealized_pnl REAL DEFAULT 0.0
        );

        -- Signal outcome tracking: links signals to trade results
        CREATE TABLE IF NOT EXISTS signal_outcomes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            signal_id INTEGER,
            timestamp TEXT NOT NULL,
            symbol TEXT NOT NULL,
            strategy TEXT NOT NULL,
            side TEXT NOT NULL,
            confidence REAL NOT NULL,
            entry_price REAL,
            exit_price REAL,
            exit_action TEXT,
            pnl REAL DEFAULT 0.0,
            pnl_pct REAL DEFAULT 0.0,
            hold_time_s REAL DEFAULT 0.0,
            regime TEXT DEFAULT '',
            leverage REAL DEFAULT 1.0,
            win INTEGER DEFAULT 0,
            score REAL DEFAULT 0.0,
            FOREIGN KEY (signal_id) REFERENCES signals(id)
        );

        -- Health events for watchdog monitoring
        CREATE TABLE IF NOT EXISTS health_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            event_type TEXT NOT NULL,
            severity TEXT NOT NULL DEFAULT 'INFO',
            message TEXT NOT NULL,
            metadata TEXT
        );

        -- Daily performance aggregation
        CREATE TABLE IF NOT EXISTS performance_daily (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            date TEXT NOT NULL,
            symbol TEXT DEFAULT 'ALL',
            strategy TEXT DEFAULT 'ALL',
            trades INTEGER DEFAULT 0,
            wins INTEGER DEFAULT 0,
            losses INTEGER DEFAULT 0,
            gross_pnl REAL DEFAULT 0.0,
            net_pnl REAL DEFAULT 0.0,
            total_fees REAL DEFAULT 0.0,
            avg_hold_time_s REAL DEFAULT 0.0,
            best_trade_pnl REAL DEFAULT 0.0,
            worst_trade_pnl REAL DEFAULT 0.0,
            avg_confidence REAL DEFAULT 0.0,
            avg_leverage REAL DEFAULT 1.0,
            UNIQUE(date, symbol, strategy)
        );

        CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
        CREATE INDEX IF NOT EXISTS idx_signals_ts ON signals(timestamp);
        CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
        CREATE INDEX IF NOT EXISTS idx_trades_ts ON trades(timestamp);
        CREATE INDEX IF NOT EXISTS idx_trades_sym_action_ts ON trades(symbol, action, timestamp);
        CREATE INDEX IF NOT EXISTS idx_equity_ts ON equity_snapshots(timestamp);
        CREATE INDEX IF NOT EXISTS idx_outcomes_symbol ON signal_outcomes(symbol);
        CREATE INDEX IF NOT EXISTS idx_outcomes_strategy ON signal_outcomes(strategy);
        CREATE INDEX IF NOT EXISTS idx_outcomes_ts ON signal_outcomes(timestamp);
        CREATE INDEX IF NOT EXISTS idx_health_ts ON health_events(timestamp);
        CREATE INDEX IF NOT EXISTS idx_health_type ON health_events(event_type);
        CREATE INDEX IF NOT EXISTS idx_perf_date ON performance_daily(date);

        -- Signal rejection audit log: every rejected signal with the gate that blocked it
        CREATE TABLE IF NOT EXISTS signal_rejections (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            symbol TEXT NOT NULL,
            strategy TEXT NOT NULL,
            side TEXT NOT NULL,
            confidence REAL NOT NULL,
            gate TEXT NOT NULL,
            reason TEXT NOT NULL,
            entry REAL DEFAULT 0.0,
            sl REAL DEFAULT 0.0,
            metadata TEXT
        );

        CREATE INDEX IF NOT EXISTS idx_rejections_ts ON signal_rejections(timestamp);
        CREATE INDEX IF NOT EXISTS idx_rejections_gate ON signal_rejections(gate);
        CREATE INDEX IF NOT EXISTS idx_rejections_symbol ON signal_rejections(symbol);
    """)
    # Run any pending schema migrations
    from data.migrations import MigrationRunner
    MigrationRunner(conn).run_pending()

    conn.close()
    logger.info(f"Database initialized: {DB_PATH}")


# ─── Write helpers ────────────────────────────────────────────────

def log_signal(symbol: str, strategy: str, side: str, confidence: float,
               entry: float = 0, sl: float = 0, tp1: float = 0, tp2: float = 0,
               atr: float = 0, leverage: float = 1.0, traded: bool = False,
               metadata: Optional[Dict] = None) -> Optional[int]:
    """Log a generated signal. Returns the signal row ID (or None on failure)."""
    conn = None
    try:
        conn = get_connection()
        cursor = conn.execute(
            """INSERT INTO signals (timestamp, symbol, strategy, side, confidence,
               entry, sl, tp1, tp2, atr, leverage, traded, metadata)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), symbol, strategy, side,
             confidence, entry, sl, tp1, tp2, atr, leverage, int(traded),
             json.dumps(metadata) if metadata else None)
        )
        conn.commit()
        return cursor.lastrowid
    except Exception as e:
        logger.warning(f"Failed to log signal: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
        return None
    finally:
        if conn:
            conn.close()


def update_signal_traded(signal_id: int, traded: bool = True):
    """Mark a signal as having been traded (position opened)."""
    conn = None
    try:
        conn = get_connection()
        conn.execute(
            "UPDATE signals SET traded = ? WHERE id = ?",
            (int(traded), signal_id)
        )
        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to update signal traded status: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


def log_trade(symbol: str, action: str, side: str, price: float,
              qty: float = 0, pnl: float = 0, fee: float = 0,
              leverage: float = 1.0, strategy: str = "",
              metadata: Optional[Dict] = None):
    """Log a trade event (OPEN, TP1, TP2, SL, TRAILING_STOP, EARLY_EXIT, etc.)."""
    conn = None
    try:
        conn = get_connection()
        conn.execute(
            """INSERT INTO trades (timestamp, symbol, action, side, price,
               qty, pnl, fee, leverage, strategy, metadata)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), symbol, action, side,
             price, qty, pnl, fee, leverage, strategy,
             json.dumps(metadata) if metadata else None)
        )
        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to log trade: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


def log_equity(equity: float, open_positions: int = 0,
               daily_pnl: float = 0, unrealized_pnl: float = 0):
    """Log an equity snapshot."""
    conn = None
    try:
        conn = get_connection()
        conn.execute(
            """INSERT INTO equity_snapshots (timestamp, equity, open_positions,
               daily_pnl, unrealized_pnl) VALUES (?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), equity, open_positions,
             daily_pnl, unrealized_pnl)
        )
        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to log equity: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


# ─── Read helpers (for summaries) ─────────────────────────────────

def get_trades_today() -> List[Dict]:
    """Get all trades from today."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM trades WHERE timestamp >= ? ORDER BY timestamp",
            (today,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_signals_today() -> List[Dict]:
    """Get all signals from today."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM signals WHERE timestamp >= ? ORDER BY timestamp",
            (today,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_recent_trades(limit: int = 10) -> List[Dict]:
    """Get most recent trades."""
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM trades WHERE action != 'OPEN' ORDER BY timestamp DESC LIMIT ?",
            (limit,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


# All actions that represent a position close (for consistent filtering)
CLOSE_ACTIONS = {"SL", "TP1", "TP2", "TRAILING_STOP", "EARLY_EXIT", "EMERGENCY",
                 "ROTATE_OUT", "ROTATE_LOSS", "MANUAL_CLOSE"}


def get_daily_summary() -> Dict[str, Any]:
    """Generate daily performance summary."""
    trades = get_trades_today()
    closes = [t for t in trades if t["action"] in CLOSE_ACTIONS]

    if not closes:
        return {"total_trades": 0, "net_pnl": 0, "win_rate": 0}

    wins = [t for t in closes if t["pnl"] > 0]
    total_pnl = sum(t["pnl"] for t in closes)
    total_fees = sum(t["fee"] for t in closes)

    # By strategy
    by_strategy = {}
    for t in closes:
        s = t.get("strategy", "unknown")
        if s not in by_strategy:
            by_strategy[s] = {"trades": 0, "wins": 0, "pnl": 0.0}
        by_strategy[s]["trades"] += 1
        if t["pnl"] > 0:
            by_strategy[s]["wins"] += 1
        by_strategy[s]["pnl"] += t["pnl"]

    # Best/worst strategy
    best = max(by_strategy.items(), key=lambda x: x[1]["pnl"]) if by_strategy else ("none", {})
    worst = min(by_strategy.items(), key=lambda x: x[1]["pnl"]) if by_strategy else ("none", {})

    return {
        "total_trades": len(closes),
        "wins": len(wins),
        "losses": len(closes) - len(wins),
        "win_rate": len(wins) / len(closes) if closes else 0,
        "net_pnl": total_pnl - total_fees,
        "total_fees": total_fees,
        "by_strategy": by_strategy,
        "best_strategy": best[0],
        "worst_strategy": worst[0],
    }


# ─── Signal Outcome Tracking ─────────────────────────────────────

def log_signal_outcome(
    symbol: str, strategy: str, side: str, confidence: float,
    entry_price: float = 0, exit_price: float = 0,
    exit_action: str = "", pnl: float = 0, pnl_pct: float = 0,
    hold_time_s: float = 0, regime: str = "", leverage: float = 1.0,
    win: bool = False, signal_id: Optional[int] = None,
) -> Optional[int]:
    """Record a signal's outcome for performance tracking."""
    # Compute a quality score: weighted combination of factors
    score = _compute_signal_score(pnl_pct, confidence, hold_time_s, win)
    conn = None
    try:
        conn = get_connection()
        cursor = conn.execute(
            """INSERT INTO signal_outcomes
               (signal_id, timestamp, symbol, strategy, side, confidence,
                entry_price, exit_price, exit_action, pnl, pnl_pct,
                hold_time_s, regime, leverage, win, score)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (signal_id, datetime.now(timezone.utc).isoformat(),
             symbol, strategy, side, confidence,
             entry_price, exit_price, exit_action, pnl, pnl_pct,
             hold_time_s, regime, leverage, int(win), score)
        )
        conn.commit()
        return cursor.lastrowid
    except Exception as e:
        logger.warning(f"Failed to log signal outcome: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
        return None
    finally:
        if conn:
            conn.close()


def _compute_signal_score(pnl_pct: float, confidence: float,
                          hold_time_s: float, win: bool) -> float:
    """Compute a quality score for a signal outcome (0-100)."""
    score = 50.0  # baseline
    # PnL contribution (capped at +/- 30 points)
    pnl_contrib = min(max(pnl_pct * 5, -30), 30)
    score += pnl_contrib
    # Confidence accuracy bonus: high confidence + win = good
    if win and confidence >= 75:
        score += 10
    elif not win and confidence >= 75:
        score -= 10  # overconfident loss
    # Hold time penalty for very long holds (> 24h)
    if hold_time_s > 86400:
        score -= 5
    return max(0, min(100, score))


def get_signal_performance(days: int = 7, symbol: str = "",
                           strategy: str = "") -> Dict[str, Any]:
    """Get signal performance stats over a period."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    conn = None
    try:
        conn = get_connection()
        query = "SELECT * FROM signal_outcomes WHERE timestamp >= ?"
        params: list = [cutoff]
        if symbol:
            query += " AND symbol = ?"
            params.append(symbol)
        if strategy:
            query += " AND strategy = ?"
            params.append(strategy)
        rows = conn.execute(query, params).fetchall()
        conn.close()

        if not rows:
            return {"total": 0, "win_rate": 0, "avg_pnl": 0, "avg_score": 0}

        outcomes = [dict(r) for r in rows]
        wins = [o for o in outcomes if o["win"]]
        total_pnl = sum(o["pnl"] for o in outcomes)
        avg_score = sum(o["score"] for o in outcomes) / len(outcomes)
        avg_conf = sum(o["confidence"] for o in outcomes) / len(outcomes)
        avg_hold = sum(o["hold_time_s"] for o in outcomes) / len(outcomes)

        # By strategy breakdown
        by_strat: Dict[str, Dict] = {}
        for o in outcomes:
            s = o["strategy"]
            if s not in by_strat:
                by_strat[s] = {"trades": 0, "wins": 0, "pnl": 0.0, "scores": []}
            by_strat[s]["trades"] += 1
            if o["win"]:
                by_strat[s]["wins"] += 1
            by_strat[s]["pnl"] += o["pnl"]
            by_strat[s]["scores"].append(o["score"])

        for s in by_strat:
            scores = by_strat[s].pop("scores")
            by_strat[s]["avg_score"] = sum(scores) / len(scores) if scores else 0
            by_strat[s]["win_rate"] = (
                by_strat[s]["wins"] / by_strat[s]["trades"]
                if by_strat[s]["trades"] > 0 else 0
            )

        # By symbol breakdown
        by_sym: Dict[str, Dict] = {}
        for o in outcomes:
            sym = o["symbol"]
            if sym not in by_sym:
                by_sym[sym] = {"trades": 0, "wins": 0, "pnl": 0.0}
            by_sym[sym]["trades"] += 1
            if o["win"]:
                by_sym[sym]["wins"] += 1
            by_sym[sym]["pnl"] += o["pnl"]
        for sym in by_sym:
            by_sym[sym]["win_rate"] = (
                by_sym[sym]["wins"] / by_sym[sym]["trades"]
                if by_sym[sym]["trades"] > 0 else 0
            )

        return {
            "total": len(outcomes),
            "wins": len(wins),
            "losses": len(outcomes) - len(wins),
            "win_rate": len(wins) / len(outcomes),
            "total_pnl": total_pnl,
            "avg_pnl": total_pnl / len(outcomes),
            "avg_score": avg_score,
            "avg_confidence": avg_conf,
            "avg_hold_time_s": avg_hold,
            "by_strategy": by_strat,
            "by_symbol": by_sym,
        }
    except Exception as e:
        logger.warning(f"Failed to get signal performance: {e}")
        return {"total": 0, "win_rate": 0, "avg_pnl": 0, "avg_score": 0}
    finally:
        if conn:
            conn.close()


def log_signal_rejection(symbol: str, strategy: str, side: str, confidence: float,
                         gate: str, reason: str, entry: float = 0, sl: float = 0,
                         metadata: Optional[Dict] = None):
    """Log a rejected signal with the gate that blocked it."""
    conn = None
    try:
        conn = get_connection()
        conn.execute(
            """INSERT INTO signal_rejections
               (timestamp, symbol, strategy, side, confidence, gate, reason, entry, sl, metadata)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), symbol, strategy, side,
             confidence, gate, reason, entry, sl,
             json.dumps(metadata) if metadata else None)
        )
        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to log signal rejection: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


def get_signal_rejections(hours: int = 1, gate: str = "", symbol: str = "") -> List[Dict]:
    """Get recent signal rejections."""
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
    try:
        conn = get_connection()
        query = "SELECT * FROM signal_rejections WHERE timestamp >= ?"
        params: list = [cutoff]
        if gate:
            query += " AND gate = ?"
            params.append(gate)
        if symbol:
            query += " AND symbol = ?"
            params.append(symbol)
        query += " ORDER BY timestamp DESC"
        rows = conn.execute(query, params).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_rejection_summary(hours: int = 1) -> Dict[str, Any]:
    """Get rejection counts by gate for the last N hours."""
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
    try:
        conn = get_connection()
        rows = conn.execute(
            """SELECT gate, COUNT(*) as count,
               SUM(CASE WHEN confidence >= 65 THEN 1 ELSE 0 END) as high_conf_count
               FROM signal_rejections WHERE timestamp >= ?
               GROUP BY gate ORDER BY count DESC""",
            (cutoff,)
        ).fetchall()
        conn.close()
        return {r["gate"]: {"count": r["count"], "high_conf": r["high_conf_count"]}
                for r in rows}
    except Exception:
        return {}


def get_equity_curve(days: int = 30) -> List[Dict]:
    """Get equity snapshots for charting."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM equity_snapshots WHERE timestamp >= ? ORDER BY timestamp",
            (cutoff,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


# ─── Health Event Tracking ────────────────────────────────────────

def log_health_event(event_type: str, severity: str, message: str,
                     metadata: Optional[Dict] = None):
    """Log a health event (stall, error, recovery, etc.)."""
    conn = None
    try:
        conn = get_connection()
        conn.execute(
            """INSERT INTO health_events (timestamp, event_type, severity, message, metadata)
               VALUES (?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), event_type, severity, message,
             json.dumps(metadata) if metadata else None)
        )
        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to log health event: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


def get_health_events(hours: int = 24, severity: str = "") -> List[Dict]:
    """Get recent health events."""
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
    try:
        conn = get_connection()
        if severity:
            rows = conn.execute(
                "SELECT * FROM health_events WHERE timestamp >= ? AND severity = ? ORDER BY timestamp DESC",
                (cutoff, severity)
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM health_events WHERE timestamp >= ? ORDER BY timestamp DESC",
                (cutoff,)
            ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


# ─── Performance Aggregation ──────────────────────────────────────

def update_daily_performance(date: str = ""):
    """Aggregate and store daily performance stats. Idempotent."""
    if not date:
        date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    conn = None
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM trades WHERE timestamp >= ? AND timestamp < ? AND action != 'OPEN'",
            (date, date + "T23:59:59Z")
        ).fetchall()

        if not rows:
            return

        trades = [dict(r) for r in rows]
        closes = [t for t in trades if t["action"] in CLOSE_ACTIONS]
        if not closes:
            return

        # Aggregate overall
        _upsert_perf(conn, date, "ALL", "ALL", closes)

        # By strategy
        strats: Dict[str, list] = {}
        for t in closes:
            s = t.get("strategy", "unknown")
            strats.setdefault(s, []).append(t)
        for s, strades in strats.items():
            _upsert_perf(conn, date, "ALL", s, strades)

        # By symbol
        syms: Dict[str, list] = {}
        for t in closes:
            syms.setdefault(t["symbol"], []).append(t)
        for sym, strades in syms.items():
            _upsert_perf(conn, date, sym, "ALL", strades)

        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to update daily performance: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


def _upsert_perf(conn, date: str, symbol: str, strategy: str,
                 closes: List[Dict]):
    """Insert or update a performance_daily row."""
    wins = [t for t in closes if t["pnl"] > 0]
    gross = sum(t["pnl"] for t in closes)
    fees = sum(t["fee"] for t in closes)
    pnls = [t["pnl"] for t in closes]

    conn.execute(
        """INSERT INTO performance_daily
           (date, symbol, strategy, trades, wins, losses,
            gross_pnl, net_pnl, total_fees,
            best_trade_pnl, worst_trade_pnl, avg_leverage)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(date, symbol, strategy) DO UPDATE SET
           trades=?, wins=?, losses=?,
           gross_pnl=?, net_pnl=?, total_fees=?,
           best_trade_pnl=?, worst_trade_pnl=?, avg_leverage=?""",
        (date, symbol, strategy,
         len(closes), len(wins), len(closes) - len(wins),
         gross, gross - fees, fees,
         max(pnls) if pnls else 0, min(pnls) if pnls else 0,
         sum(t.get("leverage", 1) for t in closes) / len(closes),
         # UPDATE values
         len(closes), len(wins), len(closes) - len(wins),
         gross, gross - fees, fees,
         max(pnls) if pnls else 0, min(pnls) if pnls else 0,
         sum(t.get("leverage", 1) for t in closes) / len(closes),
         )
    )


def get_performance_history(days: int = 30) -> List[Dict]:
    """Get daily performance history for the last N days."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%d")
    try:
        conn = get_connection()
        rows = conn.execute(
            """SELECT * FROM performance_daily
               WHERE date >= ? AND symbol = 'ALL' AND strategy = 'ALL'
               ORDER BY date""",
            (cutoff,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


# ─── Dashboard queries ────────────────────────────────────────────

def get_dashboard_data() -> Dict[str, Any]:
    """All-in-one query for web dashboard."""
    return {
        "daily_summary": get_daily_summary(),
        "recent_trades": get_recent_trades(20),
        "signals_today": get_signals_today(),
        "equity_curve": get_equity_curve(30),
        "signal_performance": get_signal_performance(7),
        "health_events": get_health_events(24),
        "performance_history": get_performance_history(30),
    }
