"""
SQLite persistence layer for trade journal, signals, equity tracking,
signal outcome scoring, and health monitoring.

Crash-proof storage that survives restarts and provides data for analysis.

Tables:
- signals: every signal generated by strategies (even non-traded ones)
- trades: every position open/close/TP/SL event
- equity_snapshots: periodic equity + position state for curve tracking
- signal_outcomes: links signals to their trade results for performance tracking
- health_events: bot health anomalies (stalls, errors, restarts)
"""

import sqlite3
import json
import logging
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple

logger = logging.getLogger("bot.db")

DB_PATH = Path("ml_data") / "bot.db"


def get_connection() -> sqlite3.Connection:
    """Get a thread-local SQLite connection."""
    conn = sqlite3.connect(str(DB_PATH), timeout=10)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")  # better concurrent reads
    return conn


def init_db():
    """Create tables if they don't exist."""
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = get_connection()
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS signals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            symbol TEXT NOT NULL,
            strategy TEXT NOT NULL,
            side TEXT NOT NULL,
            confidence REAL NOT NULL,
            entry REAL,
            sl REAL,
            tp1 REAL,
            tp2 REAL,
            atr REAL,
            leverage REAL DEFAULT 1.0,
            traded INTEGER DEFAULT 0,
            metadata TEXT
        );

        CREATE TABLE IF NOT EXISTS trades (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            symbol TEXT NOT NULL,
            action TEXT NOT NULL,
            side TEXT NOT NULL,
            price REAL NOT NULL,
            qty REAL,
            pnl REAL DEFAULT 0.0,
            fee REAL DEFAULT 0.0,
            leverage REAL DEFAULT 1.0,
            strategy TEXT,
            metadata TEXT
        );

        CREATE TABLE IF NOT EXISTS equity_snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            equity REAL NOT NULL,
            open_positions INTEGER DEFAULT 0,
            daily_pnl REAL DEFAULT 0.0,
            unrealized_pnl REAL DEFAULT 0.0
        );

        CREATE TABLE IF NOT EXISTS signal_outcomes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            signal_id INTEGER NOT NULL,
            symbol TEXT NOT NULL,
            strategy TEXT NOT NULL,
            side TEXT NOT NULL,
            confidence REAL NOT NULL,
            entry_price REAL,
            exit_price REAL,
            exit_action TEXT,
            pnl REAL DEFAULT 0.0,
            hold_time_s REAL DEFAULT 0.0,
            outcome TEXT,
            scored_at TEXT NOT NULL,
            FOREIGN KEY (signal_id) REFERENCES signals(id)
        );

        CREATE TABLE IF NOT EXISTS health_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            event_type TEXT NOT NULL,
            severity TEXT NOT NULL DEFAULT 'warning',
            message TEXT,
            details TEXT
        );

        CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
        CREATE INDEX IF NOT EXISTS idx_signals_ts ON signals(timestamp);
        CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
        CREATE INDEX IF NOT EXISTS idx_trades_ts ON trades(timestamp);
        CREATE INDEX IF NOT EXISTS idx_trades_sym_action_ts ON trades(symbol, action, timestamp);
        CREATE INDEX IF NOT EXISTS idx_equity_ts ON equity_snapshots(timestamp);
        CREATE INDEX IF NOT EXISTS idx_signal_outcomes_symbol ON signal_outcomes(symbol);
        CREATE INDEX IF NOT EXISTS idx_signal_outcomes_strategy ON signal_outcomes(strategy);
        CREATE INDEX IF NOT EXISTS idx_signal_outcomes_scored ON signal_outcomes(scored_at);
        CREATE INDEX IF NOT EXISTS idx_health_ts ON health_events(timestamp);
        CREATE INDEX IF NOT EXISTS idx_health_type ON health_events(event_type);
    """)
    conn.close()
    logger.info(f"Database initialized: {DB_PATH}")


# ─── Write helpers ────────────────────────────────────────────────

def log_signal(symbol: str, strategy: str, side: str, confidence: float,
               entry: float = 0, sl: float = 0, tp1: float = 0, tp2: float = 0,
               atr: float = 0, leverage: float = 1.0, traded: bool = False,
               metadata: Optional[Dict] = None) -> Optional[int]:
    """Log a generated signal. Returns the signal row ID (or None on failure)."""
    conn = None
    try:
        conn = get_connection()
        cursor = conn.execute(
            """INSERT INTO signals (timestamp, symbol, strategy, side, confidence,
               entry, sl, tp1, tp2, atr, leverage, traded, metadata)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), symbol, strategy, side,
             confidence, entry, sl, tp1, tp2, atr, leverage, int(traded),
             json.dumps(metadata) if metadata else None)
        )
        conn.commit()
        return cursor.lastrowid
    except Exception as e:
        logger.warning(f"Failed to log signal: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
        return None
    finally:
        if conn:
            conn.close()


def update_signal_traded(signal_id: int, traded: bool = True):
    """Mark a signal as having been traded (position opened)."""
    conn = None
    try:
        conn = get_connection()
        conn.execute(
            "UPDATE signals SET traded = ? WHERE id = ?",
            (int(traded), signal_id)
        )
        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to update signal traded status: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


def log_trade(symbol: str, action: str, side: str, price: float,
              qty: float = 0, pnl: float = 0, fee: float = 0,
              leverage: float = 1.0, strategy: str = "",
              metadata: Optional[Dict] = None):
    """Log a trade event (OPEN, TP1, TP2, SL, TRAILING_STOP, EARLY_EXIT, etc.)."""
    conn = None
    try:
        conn = get_connection()
        conn.execute(
            """INSERT INTO trades (timestamp, symbol, action, side, price,
               qty, pnl, fee, leverage, strategy, metadata)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), symbol, action, side,
             price, qty, pnl, fee, leverage, strategy,
             json.dumps(metadata) if metadata else None)
        )
        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to log trade: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


def log_equity(equity: float, open_positions: int = 0,
               daily_pnl: float = 0, unrealized_pnl: float = 0):
    """Log an equity snapshot."""
    conn = None
    try:
        conn = get_connection()
        conn.execute(
            """INSERT INTO equity_snapshots (timestamp, equity, open_positions,
               daily_pnl, unrealized_pnl) VALUES (?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), equity, open_positions,
             daily_pnl, unrealized_pnl)
        )
        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to log equity: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


# ─── Read helpers (for summaries) ─────────────────────────────────

def get_trades_today() -> List[Dict]:
    """Get all trades from today."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM trades WHERE timestamp >= ? ORDER BY timestamp",
            (today,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_signals_today() -> List[Dict]:
    """Get all signals from today."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM signals WHERE timestamp >= ? ORDER BY timestamp",
            (today,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_recent_trades(limit: int = 10) -> List[Dict]:
    """Get most recent trades."""
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM trades WHERE action != 'OPEN' ORDER BY timestamp DESC LIMIT ?",
            (limit,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


# All actions that represent a position close (for consistent filtering)
CLOSE_ACTIONS = {"SL", "TP1", "TP2", "TRAILING_STOP", "EARLY_EXIT", "EMERGENCY",
                 "ROTATE_OUT", "ROTATE_LOSS", "MANUAL_CLOSE"}


def get_daily_summary() -> Dict[str, Any]:
    """Generate daily performance summary."""
    trades = get_trades_today()
    closes = [t for t in trades if t["action"] in CLOSE_ACTIONS]

    if not closes:
        return {"total_trades": 0, "net_pnl": 0, "win_rate": 0}

    wins = [t for t in closes if t["pnl"] > 0]
    total_pnl = sum(t["pnl"] for t in closes)
    total_fees = sum(t["fee"] for t in closes)

    # By strategy
    by_strategy = {}
    for t in closes:
        s = t.get("strategy", "unknown")
        if s not in by_strategy:
            by_strategy[s] = {"trades": 0, "wins": 0, "pnl": 0.0}
        by_strategy[s]["trades"] += 1
        if t["pnl"] > 0:
            by_strategy[s]["wins"] += 1
        by_strategy[s]["pnl"] += t["pnl"]

    # Best/worst strategy
    best = max(by_strategy.items(), key=lambda x: x[1]["pnl"]) if by_strategy else ("none", {})
    worst = min(by_strategy.items(), key=lambda x: x[1]["pnl"]) if by_strategy else ("none", {})

    return {
        "total_trades": len(closes),
        "wins": len(wins),
        "losses": len(closes) - len(wins),
        "win_rate": len(wins) / len(closes) if closes else 0,
        "net_pnl": total_pnl - total_fees,
        "total_fees": total_fees,
        "by_strategy": by_strategy,
        "best_strategy": best[0],
        "worst_strategy": worst[0],
    }


# ─── Signal Outcome Tracking ────────────────────────────────────

def log_signal_outcome(signal_id: int, symbol: str, strategy: str, side: str,
                       confidence: float, entry_price: float = 0,
                       exit_price: float = 0, exit_action: str = "",
                       pnl: float = 0, hold_time_s: float = 0,
                       outcome: str = ""):
    """Record the outcome of a traded signal for performance scoring."""
    conn = None
    try:
        conn = get_connection()
        conn.execute(
            """INSERT INTO signal_outcomes
               (signal_id, symbol, strategy, side, confidence, entry_price,
                exit_price, exit_action, pnl, hold_time_s, outcome, scored_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (signal_id, symbol, strategy, side, confidence, entry_price,
             exit_price, exit_action, pnl, hold_time_s, outcome,
             datetime.now(timezone.utc).isoformat())
        )
        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to log signal outcome: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


def get_signal_performance(days: int = 30) -> Dict[str, Any]:
    """Get signal performance stats: which strategies/symbols/confidence bands win."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    try:
        conn = get_connection()

        # Overall stats
        rows = conn.execute(
            "SELECT outcome, COUNT(*) as cnt, SUM(pnl) as total_pnl "
            "FROM signal_outcomes WHERE scored_at >= ? GROUP BY outcome",
            (cutoff,)
        ).fetchall()
        overall = {r["outcome"]: {"count": r["cnt"], "pnl": r["total_pnl"]} for r in rows}

        # By strategy
        rows = conn.execute(
            "SELECT strategy, outcome, COUNT(*) as cnt, SUM(pnl) as total_pnl "
            "FROM signal_outcomes WHERE scored_at >= ? GROUP BY strategy, outcome",
            (cutoff,)
        ).fetchall()
        by_strategy = {}
        for r in rows:
            s = r["strategy"]
            if s not in by_strategy:
                by_strategy[s] = {"wins": 0, "losses": 0, "pnl": 0.0}
            if r["outcome"] == "WIN":
                by_strategy[s]["wins"] = r["cnt"]
            else:
                by_strategy[s]["losses"] = r["cnt"]
            by_strategy[s]["pnl"] += r["total_pnl"]

        # By confidence band
        rows = conn.execute(
            """SELECT
                CASE
                    WHEN confidence >= 85 THEN 'high_85+'
                    WHEN confidence >= 75 THEN 'med_75-84'
                    WHEN confidence >= 65 THEN 'low_65-74'
                    ELSE 'weak_<65'
                END as band,
                COUNT(*) as cnt,
                SUM(CASE WHEN outcome = 'WIN' THEN 1 ELSE 0 END) as wins,
                SUM(pnl) as total_pnl
            FROM signal_outcomes WHERE scored_at >= ?
            GROUP BY band""",
            (cutoff,)
        ).fetchall()
        by_confidence = {r["band"]: {"total": r["cnt"], "wins": r["wins"],
                                      "win_rate": r["wins"] / r["cnt"] if r["cnt"] > 0 else 0,
                                      "pnl": r["total_pnl"]} for r in rows}

        # By symbol
        rows = conn.execute(
            "SELECT symbol, COUNT(*) as cnt, "
            "SUM(CASE WHEN outcome = 'WIN' THEN 1 ELSE 0 END) as wins, "
            "SUM(pnl) as total_pnl "
            "FROM signal_outcomes WHERE scored_at >= ? GROUP BY symbol",
            (cutoff,)
        ).fetchall()
        by_symbol = {r["symbol"]: {"total": r["cnt"], "wins": r["wins"],
                                    "win_rate": r["wins"] / r["cnt"] if r["cnt"] > 0 else 0,
                                    "pnl": r["total_pnl"]} for r in rows}

        conn.close()

        total_trades = sum(v.get("count", 0) for v in overall.values())
        total_wins = overall.get("WIN", {}).get("count", 0)

        return {
            "period_days": days,
            "total_outcomes": total_trades,
            "wins": total_wins,
            "losses": total_trades - total_wins,
            "win_rate": total_wins / total_trades if total_trades > 0 else 0,
            "total_pnl": sum(v.get("pnl", 0) for v in overall.values()),
            "by_strategy": by_strategy,
            "by_confidence": by_confidence,
            "by_symbol": by_symbol,
        }
    except Exception as e:
        logger.warning(f"Failed to get signal performance: {e}")
        return {}


# ─── Equity Curve Queries ────────────────────────────────────────

def get_equity_curve(hours: int = 168) -> List[Dict]:
    """Get equity snapshots for the last N hours (default 7 days)."""
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT timestamp, equity, open_positions, daily_pnl, unrealized_pnl "
            "FROM equity_snapshots WHERE timestamp >= ? ORDER BY timestamp",
            (cutoff,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_recent_signals(limit: int = 20) -> List[Dict]:
    """Get most recent signals (for dashboard display)."""
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM signals ORDER BY timestamp DESC LIMIT ?",
            (limit,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


# ─── Health Event Logging ────────────────────────────────────────

def log_health_event(event_type: str, severity: str = "warning",
                     message: str = "", details: Optional[Dict] = None):
    """Log a health event (stall, error, restart, etc.)."""
    conn = None
    try:
        conn = get_connection()
        conn.execute(
            "INSERT INTO health_events (timestamp, event_type, severity, message, details) "
            "VALUES (?, ?, ?, ?, ?)",
            (datetime.now(timezone.utc).isoformat(), event_type, severity,
             message, json.dumps(details) if details else None)
        )
        conn.commit()
    except Exception as e:
        logger.warning(f"Failed to log health event: {e}")
        if conn:
            try:
                conn.rollback()
            except Exception:
                pass
    finally:
        if conn:
            conn.close()


def get_health_events(hours: int = 24) -> List[Dict]:
    """Get recent health events."""
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat()
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM health_events WHERE timestamp >= ? ORDER BY timestamp DESC",
            (cutoff,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


# ─── Strategy Performance (aggregated from signal outcomes) ──────

def get_strategy_leaderboard(days: int = 7) -> List[Dict]:
    """Get strategy ranking by profitability for the last N days."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    try:
        conn = get_connection()
        rows = conn.execute(
            """SELECT strategy,
                      COUNT(*) as trades,
                      SUM(CASE WHEN outcome = 'WIN' THEN 1 ELSE 0 END) as wins,
                      SUM(pnl) as total_pnl,
                      AVG(pnl) as avg_pnl,
                      AVG(hold_time_s) as avg_hold_s
               FROM signal_outcomes
               WHERE scored_at >= ?
               GROUP BY strategy
               ORDER BY total_pnl DESC""",
            (cutoff,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []
