"""
SQLite persistence layer for trade journal, signals, and equity tracking.
Crash-proof storage that survives restarts and provides data for analysis.

Tables:
- signals: every signal generated by strategies (even non-traded ones)
- trades: every position open/close/TP/SL event
- equity_snapshots: periodic equity + position state for curve tracking
"""

import sqlite3
import json
import logging
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, List, Optional

logger = logging.getLogger("bot.db")

DB_PATH = Path("ml_data") / "bot.db"


def get_connection() -> sqlite3.Connection:
    """Get a thread-local SQLite connection."""
    conn = sqlite3.connect(str(DB_PATH), timeout=10)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")  # better concurrent reads
    return conn


def init_db():
    """Create tables if they don't exist."""
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = get_connection()
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS signals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            symbol TEXT NOT NULL,
            strategy TEXT NOT NULL,
            side TEXT NOT NULL,
            confidence REAL NOT NULL,
            entry REAL,
            sl REAL,
            tp1 REAL,
            tp2 REAL,
            atr REAL,
            leverage REAL DEFAULT 1.0,
            traded INTEGER DEFAULT 0,
            metadata TEXT
        );

        CREATE TABLE IF NOT EXISTS trades (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            symbol TEXT NOT NULL,
            action TEXT NOT NULL,
            side TEXT NOT NULL,
            price REAL NOT NULL,
            qty REAL,
            pnl REAL DEFAULT 0.0,
            fee REAL DEFAULT 0.0,
            leverage REAL DEFAULT 1.0,
            strategy TEXT,
            metadata TEXT
        );

        CREATE TABLE IF NOT EXISTS equity_snapshots (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            equity REAL NOT NULL,
            open_positions INTEGER DEFAULT 0,
            daily_pnl REAL DEFAULT 0.0,
            unrealized_pnl REAL DEFAULT 0.0
        );

        CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals(symbol);
        CREATE INDEX IF NOT EXISTS idx_signals_ts ON signals(timestamp);
        CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
        CREATE INDEX IF NOT EXISTS idx_trades_ts ON trades(timestamp);
        CREATE INDEX IF NOT EXISTS idx_equity_ts ON equity_snapshots(timestamp);
    """)
    conn.close()
    logger.info(f"Database initialized: {DB_PATH}")


# ─── Write helpers ────────────────────────────────────────────────

def log_signal(symbol: str, strategy: str, side: str, confidence: float,
               entry: float = 0, sl: float = 0, tp1: float = 0, tp2: float = 0,
               atr: float = 0, leverage: float = 1.0, traded: bool = False,
               metadata: Optional[Dict] = None):
    """Log a generated signal."""
    try:
        conn = get_connection()
        conn.execute(
            """INSERT INTO signals (timestamp, symbol, strategy, side, confidence,
               entry, sl, tp1, tp2, atr, leverage, traded, metadata)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), symbol, strategy, side,
             confidence, entry, sl, tp1, tp2, atr, leverage, int(traded),
             json.dumps(metadata) if metadata else None)
        )
        conn.commit()
        conn.close()
    except Exception as e:
        logger.warning(f"Failed to log signal: {e}")


def log_trade(symbol: str, action: str, side: str, price: float,
              qty: float = 0, pnl: float = 0, fee: float = 0,
              leverage: float = 1.0, strategy: str = "",
              metadata: Optional[Dict] = None):
    """Log a trade event (OPEN, TP1, TP2, SL, TRAILING_STOP)."""
    try:
        conn = get_connection()
        conn.execute(
            """INSERT INTO trades (timestamp, symbol, action, side, price,
               qty, pnl, fee, leverage, strategy, metadata)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), symbol, action, side,
             price, qty, pnl, fee, leverage, strategy,
             json.dumps(metadata) if metadata else None)
        )
        conn.commit()
        conn.close()
    except Exception as e:
        logger.warning(f"Failed to log trade: {e}")


def log_equity(equity: float, open_positions: int = 0,
               daily_pnl: float = 0, unrealized_pnl: float = 0):
    """Log an equity snapshot."""
    try:
        conn = get_connection()
        conn.execute(
            """INSERT INTO equity_snapshots (timestamp, equity, open_positions,
               daily_pnl, unrealized_pnl) VALUES (?, ?, ?, ?, ?)""",
            (datetime.now(timezone.utc).isoformat(), equity, open_positions,
             daily_pnl, unrealized_pnl)
        )
        conn.commit()
        conn.close()
    except Exception as e:
        logger.warning(f"Failed to log equity: {e}")


# ─── Read helpers (for summaries) ─────────────────────────────────

def get_trades_today() -> List[Dict]:
    """Get all trades from today."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM trades WHERE timestamp >= ? ORDER BY timestamp",
            (today,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_signals_today() -> List[Dict]:
    """Get all signals from today."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM signals WHERE timestamp >= ? ORDER BY timestamp",
            (today,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_recent_trades(limit: int = 10) -> List[Dict]:
    """Get most recent trades."""
    try:
        conn = get_connection()
        rows = conn.execute(
            "SELECT * FROM trades WHERE action != 'OPEN' ORDER BY timestamp DESC LIMIT ?",
            (limit,)
        ).fetchall()
        conn.close()
        return [dict(r) for r in rows]
    except Exception:
        return []


def get_daily_summary() -> Dict[str, Any]:
    """Generate daily performance summary."""
    trades = get_trades_today()
    closes = [t for t in trades if t["action"] in ("SL", "TP1", "TP2", "TRAILING_STOP")]

    if not closes:
        return {"total_trades": 0, "net_pnl": 0, "win_rate": 0}

    wins = [t for t in closes if t["pnl"] > 0]
    total_pnl = sum(t["pnl"] for t in closes)
    total_fees = sum(t["fee"] for t in closes)

    # By strategy
    by_strategy = {}
    for t in closes:
        s = t.get("strategy", "unknown")
        if s not in by_strategy:
            by_strategy[s] = {"trades": 0, "wins": 0, "pnl": 0.0}
        by_strategy[s]["trades"] += 1
        if t["pnl"] > 0:
            by_strategy[s]["wins"] += 1
        by_strategy[s]["pnl"] += t["pnl"]

    # Best/worst strategy
    best = max(by_strategy.items(), key=lambda x: x[1]["pnl"]) if by_strategy else ("none", {})
    worst = min(by_strategy.items(), key=lambda x: x[1]["pnl"]) if by_strategy else ("none", {})

    return {
        "total_trades": len(closes),
        "wins": len(wins),
        "losses": len(closes) - len(wins),
        "win_rate": len(wins) / len(closes) if closes else 0,
        "net_pnl": total_pnl - total_fees,
        "total_fees": total_fees,
        "by_strategy": by_strategy,
        "best_strategy": best[0],
        "worst_strategy": worst[0],
    }
