#!/usr/bin/env python3
"""
Generate concrete fixes based on autonomous analysis findings.

Fixes:
1. Add illiquid regime filter to signal pipeline (gate 1)
2. Audit and fix leverage sizing logic
3. Flag confidence calibration issue for review
4. Recommend regime detector validation
"""

import json
from datetime import datetime

def generate_illiquid_filter_gate():
    """Generate gate that filters illiquid regime trades."""
    gate_code = '''# Generated by autonomous analysis 2026-06-05
# Issue: Illiquid regime has 48% of trades, loses -$1,865 (50% of total losses)
# Solution: Block illiquid regime at gate 1 (signal validity)

def check_regime_valid(signal, market_state) -> bool:
    """Gate 1: Block known-losing regimes."""
    regime = market_state.get('regime', 'unknown')

    # Based on analysis: only trending regime is profitable
    ALLOWED_REGIMES = ['trending']  # Can add 'ranging' if revalidated
    BLOCKED_REGIMES = ['illiquid', 'unknown']

    if regime in BLOCKED_REGIMES:
        return False, f"regime_block: {regime} is losing regime"

    return True, "regime_pass"
'''
    return gate_code

def generate_leverage_audit_report():
    """Generate leverage sizing audit findings."""
    report = {
        'issue': 'Leverage sizing misaligned with outcomes',
        'timestamp': datetime.utcnow().isoformat(),
        'findings': [
            {
                'leverage': '1x-2x',
                'trades': 8,
                'pnl': -269.94,
                'wr': 0.125,
                'issue': 'Too low leverage, but still losing'
            },
            {
                'leverage': '5x',
                'trades': 136,
                'pnl': -3175.90,
                'wr': 0.287,
                'issue': 'TOXIC: 85% of total losses. Concentration risk.'
            },
            {
                'leverage': '3x',
                'trades': 5,
                'pnl': 53.01,
                'wr': 0.40,
                'issue': 'PROFITABLE: Only 5 trades but best unit WR'
            },
            {
                'leverage': '7x-10x',
                'trades': 24,
                'pnl': 88.71,
                'wr': 0.375,
                'issue': 'Profitable. Higher leverage + better regimes?'
            }
        ],
        'root_cause_hypothesis': 'High leverage (5x) was applied uniformly across all regimes. In illiquid regime, 5x magnifies already-losing signals.',
        'recommended_action': 'Tier leverage by regime: 3x in ranging, 1x-2x in illiquid (or skip), higher in trending'
    }
    return report

def generate_confidence_investigation():
    """Flag the inverted confidence calibration issue."""
    investigation = {
        'issue': 'Confidence scores do not predict outcomes',
        'timestamp': datetime.utcnow().isoformat(),
        'data': {
            'low_confidence': {
                'range': '<50',
                'trades': 75,
                'pnl': -1490.49,
                'wr': 0.173,
                'avg_pnl_per_trade': -19.87
            },
            'high_confidence': {
                'range': '>=50',
                'trades': 153,
                'pnl': -2224.50,
                'wr': 0.320,
                'avg_pnl_per_trade': -14.54
            }
        },
        'anomaly': 'High confidence trades lose MORE money despite higher WR',
        'possible_causes': [
            'Size overestimation in high-confidence setup',
            'Kelly weights not accounting for frequency',
            'Position sizing too aggressive when confident'
        ],
        'investigation_needed': 'Check position sizing logic in Risk Agent'
    }
    return investigation

def main():
    print("[GENERATING FIXES FROM ANALYSIS]")
    print()

    # Fix 1: Illiquid filter
    print("1. ILLIQUID REGIME FILTER")
    print("-" * 60)
    gate = generate_illiquid_filter_gate()
    print(gate)
    print()

    # Fix 2: Leverage audit
    print("2. LEVERAGE SIZING AUDIT")
    print("-" * 60)
    lev_report = generate_leverage_audit_report()
    print(json.dumps(lev_report, indent=2, default=str))
    print()

    # Fix 3: Confidence investigation
    print("3. CONFIDENCE CALIBRATION ISSUE")
    print("-" * 60)
    conf_investigation = generate_confidence_investigation()
    print(json.dumps(conf_investigation, indent=2, default=str))
    print()

    # Save all to KB
    kb = {
        'timestamp': datetime.utcnow().isoformat(),
        'illiquid_filter': gate,
        'leverage_audit': lev_report,
        'confidence_issue': conf_investigation,
    }

    with open('./bot/data/generated_fixes.json', 'w') as f:
        json.dump(kb, f, indent=2, default=str)
    print("[OK] Fixes saved to bot/data/generated_fixes.json")

if __name__ == '__main__':
    main()
