"""
Trade and signal logger for paper trading + backtesting validation.

Logs:
- Every signal generated (entry, stop, targets, confidence)
- Every trade event (open, TP1, TP2, SL, trailing stop)
- Final P&L and statistics

Usage:
    logger = TradeLogger("paper_trades.csv")
    logger.log_signal(signal)
    logger.log_trade_event(event)
    report = logger.generate_report()
"""

import csv
import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, asdict

logger = logging.getLogger("bot.execution.trade_logger")


@dataclass
class SignalLog:
    """Record of a signal generated."""
    timestamp: str
    trace_id: str
    symbol: str
    strategy: str  # ensemble or individual strategy name
    side: str       # BUY or SELL
    confidence: float
    entry: float
    sl: float
    tp1: float
    tp2: float
    atr: float
    regime_score: float  # Added info from ensemble
    num_agree: int       # How many strategies agreed
    total_strategies: int


@dataclass
class TradeLog:
    """Record of a trade action."""
    timestamp: str
    symbol: str
    action: str      # OPEN, TP1, TP2, SL, TRAILING_STOP
    side: str        # LONG or SHORT
    price: float
    qty: float
    pnl: float
    fee: float
    leverage: float
    hold_time_s: int


class TradeLogger:
    """Logs signals and trades for analysis."""

    def __init__(self, log_dir: str = "paper_trades"):
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(exist_ok=True)

        self.signals_file = self.log_dir / f"signals_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        self.trades_file = self.log_dir / f"trades_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"

        self.signals: List[SignalLog] = []
        self.trades: List[TradeLog] = []

        # Initialize CSV files with headers
        self._init_signals_csv()
        self._init_trades_csv()

    def _init_signals_csv(self):
        """Create signals CSV with headers."""
        headers = [f.name for f in SignalLog.__dataclass_fields__.values()]
        with open(self.signals_file, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=headers)
            writer.writeheader()

    def _init_trades_csv(self):
        """Create trades CSV with headers."""
        headers = [f.name for f in TradeLog.__dataclass_fields__.values()]
        with open(self.trades_file, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=headers)
            writer.writeheader()

    def log_signal(
        self,
        symbol: str,
        signal_obj: Any,  # strategies.base.Signal
        trace_id: str = "",
        regime_score: float = 0.0,
        num_agree: int = 1,
        total_strategies: int = 4,
    ):
        """Log a signal generated by the ensemble."""
        log = SignalLog(
            timestamp=datetime.now(timezone.utc).isoformat(),
            trace_id=trace_id,
            symbol=symbol,
            strategy="ensemble",
            side=signal_obj.side,
            confidence=signal_obj.confidence,
            entry=signal_obj.entry,
            sl=signal_obj.sl,
            tp1=signal_obj.tp1,
            tp2=signal_obj.tp2,
            atr=signal_obj.atr,
            regime_score=regime_score,
            num_agree=num_agree,
            total_strategies=total_strategies,
        )
        self.signals.append(log)
        self._append_to_csv(self.signals_file, asdict(log))

    def log_trade_event(
        self,
        event: Any,  # execution.position_manager.TradeEvent
        hold_time_s: int = 0,
    ):
        """Log a trade action (open, close, TP hit, SL hit)."""
        log = TradeLog(
            timestamp=datetime.now(timezone.utc).isoformat(),
            symbol=event.symbol,
            action=event.action,
            side=event.side,
            price=event.price,
            qty=event.qty,
            pnl=event.pnl,
            fee=event.fee,
            leverage=event.leverage,
            hold_time_s=hold_time_s,
        )
        self.trades.append(log)
        self._append_to_csv(self.trades_file, asdict(log))

    def _append_to_csv(self, filepath: Path, row_dict: Dict):
        """Append a row to a CSV file."""
        try:
            with open(filepath, "a", newline="") as f:
                fieldnames = list(row_dict.keys())
                writer = csv.DictWriter(f, fieldnames=fieldnames)
                writer.writerow(row_dict)
        except Exception as e:
            logger.error(f"Failed to write to {filepath}: {e}")

    def generate_report(self) -> Dict[str, Any]:
        """Generate performance statistics from logged trades."""
        if not self.trades:
            return {"error": "No trades logged yet"}

        # Group trades by symbol and action
        closing_trades = [t for t in self.trades if t.action in ("TP1", "TP2", "SL", "TRAILING_STOP")]
        if not closing_trades:
            return {"error": "No closed trades yet"}

        # Calculate statistics
        total_trades = len(closing_trades)
        winning_trades = [t for t in closing_trades if t.pnl > 0]
        losing_trades = [t for t in closing_trades if t.pnl < 0]
        break_even = len([t for t in closing_trades if t.pnl == 0])

        win_count = len(winning_trades)
        loss_count = len(losing_trades)
        win_rate = (win_count / total_trades * 100) if total_trades > 0 else 0

        total_pnl = sum(t.pnl for t in closing_trades)
        total_fees = sum(t.fee for t in closing_trades)
        gross_pnl = total_pnl + total_fees

        # Risk/Reward analysis
        avg_win = sum(t.pnl for t in winning_trades) / len(winning_trades) if winning_trades else 0
        avg_loss = sum(t.pnl for t in losing_trades) / len(losing_trades) if losing_trades else 0

        # Find consecutive wins/losses
        max_consecutive_wins = self._max_consecutive(closing_trades, True)
        max_consecutive_losses = self._max_consecutive(closing_trades, False)

        # By symbol
        by_symbol = {}
        for symbol in set(t.symbol for t in closing_trades):
            sym_trades = [t for t in closing_trades if t.symbol == symbol]
            sym_wins = [t for t in sym_trades if t.pnl > 0]
            by_symbol[symbol] = {
                "trades": len(sym_trades),
                "wins": len(sym_wins),
                "win_rate": len(sym_wins) / len(sym_trades) * 100 if sym_trades else 0,
                "pnl": sum(t.pnl for t in sym_trades),
            }

        # By action (how exits are performing)
        by_action = {}
        for action in set(t.action for t in closing_trades):
            act_trades = [t for t in closing_trades if t.action == action]
            act_wins = [t for t in act_trades if t.pnl > 0]
            by_action[action] = {
                "exits": len(act_trades),
                "wins": len(act_wins),
                "win_rate": len(act_wins) / len(act_trades) * 100 if act_trades else 0,
                "avg_pnl": sum(t.pnl for t in act_trades) / len(act_trades) if act_trades else 0,
            }

        report = {
            "date_generated": datetime.now(timezone.utc).isoformat(),
            "summary": {
                "total_closed_trades": total_trades,
                "wins": win_count,
                "losses": loss_count,
                "break_even": break_even,
                "win_rate_pct": round(win_rate, 2),
                "max_consecutive_wins": max_consecutive_wins,
                "max_consecutive_losses": max_consecutive_losses,
            },
            "pnl": {
                "gross_pnl": round(gross_pnl, 2),
                "net_pnl": round(total_pnl, 2),
                "total_fees": round(total_fees, 2),
                "avg_win": round(avg_win, 2),
                "avg_loss": round(avg_loss, 2),
                "profit_factor": round(
                    sum(t.pnl for t in winning_trades) / abs(sum(t.pnl for t in losing_trades))
                    if losing_trades and sum(t.pnl for t in losing_trades) != 0 else 0,
                    2
                ),
            },
            "by_symbol": by_symbol,
            "by_action": by_action,
            "logs": {
                "signals_file": str(self.signals_file),
                "trades_file": str(self.trades_file),
            },
        }

        return report

    def _max_consecutive(self, trades: List[TradeLog], is_win: bool) -> int:
        """Find max consecutive wins or losses."""
        max_streak = 0
        current_streak = 0
        for trade in trades:
            is_profitable = trade.pnl > 0
            if (is_profitable and is_win) or (not is_profitable and not is_win):
                current_streak += 1
                max_streak = max(max_streak, current_streak)
            else:
                current_streak = 0
        return max_streak

    def print_report(self, report: Optional[Dict] = None):
        """Pretty-print the report."""
        if report is None:
            report = self.generate_report()

        if "error" in report:
            print(f"❌ {report['error']}")
            return

        print("\n" + "=" * 60)
        print("PAPER TRADING PERFORMANCE REPORT")
        print("=" * 60)
        print(f"Generated: {report['date_generated']}")

        print("\n📊 SUMMARY:")
        summary = report["summary"]
        print(f"  Total Trades: {summary['total_closed_trades']}")
        print(f"  Wins: {summary['wins']} | Losses: {summary['losses']} | Break-even: {summary['break_even']}")
        print(f"  Win Rate: {summary['win_rate_pct']}%")
        print(f"  Max Consecutive Wins: {summary['max_consecutive_wins']}")
        print(f"  Max Consecutive Losses: {summary['max_consecutive_losses']}")

        print("\n💵 PNL:")
        pnl = report["pnl"]
        print(f"  Gross P&L: ${pnl['gross_pnl']:+.2f}")
        print(f"  Net P&L: ${pnl['net_pnl']:+.2f} (after ${pnl['total_fees']:.2f} fees)")
        print(f"  Avg Win: ${pnl['avg_win']:+.2f}")
        print(f"  Avg Loss: ${pnl['avg_loss']:+.2f}")
        print(f"  Profit Factor: {pnl['profit_factor']:.2f}x")

        print("\n📈 BY SYMBOL:")
        for symbol, stats in report["by_symbol"].items():
            print(f"  {symbol}: {stats['trades']} trades | {stats['win_rate']:.1f}% WR | P&L: ${stats['pnl']:+.2f}")

        print("\n📉 BY EXIT TYPE:")
        for action, stats in report["by_action"].items():
            print(f"  {action}: {stats['exits']} exits | {stats['win_rate']:.1f}% WR | Avg P&L: ${stats['avg_pnl']:+.2f}")

        print(f"\n📁 Logs saved to:")
        print(f"  Signals: {report['logs']['signals_file']}")
        print(f"  Trades: {report['logs']['trades_file']}")
        print("=" * 60 + "\n")
